def binary(key, value):
    if value == '0' or value == '1':
        return 'ok'
    else:
        return 'Invalid value: %s, must be 1 or 0' % value


def constant(key, value):
    return 'You can\'t change this key: %s' % key


def free(key, value):
    return 'ok'


def percentage(key, value, start=0, end=100):
    tmp_value = value.rstrip('%')
    return int_range(key, value, start, end)


def float_range(key, value, start=float('-inf'), end=float('inf')):
    try:
        tmp_value = float(value)
    except:
        return 'Invalid value: %s, must be a float' % value
    else:
        if start <= tmp_value and tmp_value <= end:
            return 'ok'
        else:
            return 'Invalid value: %s, must be within [%f-%f]' % (value, start, end)


def int_range(key, value, start=float('-inf'), end=float('inf')):
    try:
        tmp_value = int(value)
    except:
        return 'Invalid value: %s, must be a integer' % value
    else:
        if start <= tmp_value and tmp_value <= end:
            return 'ok'
        else:
            return 'Invalid value: %s, must be within [%d-%d]' % (value, start, end)

ini_string = '# generated by Slic3r 1.2.9 on Sun Aug 23 18:31:49 2015\n\
avoid_crossing_perimeters = 0\n\
bed_shape = 84.5344x8.88492,83.1425x17.6725,80.8398x26.2664,77.6514x34.5726,73.6122x42.5,68.7664x49.9617,63.1673x56.8761,56.8761x63.1673,49.9617x68.7664,42.5x73.6122,34.5726x77.6514,26.2664x80.8398,17.6725x83.1425,8.88492x84.5344,0x85,-8.88492x84.5344,-17.6725x83.1425,-26.2664x80.8398,-34.5726x77.6514,-42.5x73.6122,-49.9617x68.7664,-56.8761x63.1673,-63.1673x56.8761,-68.7664x49.9617,-73.6122x42.5,-77.6514x34.5726,-80.8398x26.2664,-83.1425x17.6725,-84.5344x8.88492,-85x0,-84.5344x-8.88492,-83.1425x-17.6725,-80.8398x-26.2664,-77.6514x-34.5726,-73.6122x-42.5,-68.7664x-49.9617,-63.1673x-56.8761,-56.8761x-63.1673,-49.9617x-68.7664,-42.5x-73.6122,-34.5726x-77.6514,-26.2664x-80.8398,-17.6725x-83.1425,-8.88492x-84.5344,0x-85,8.88492x-84.5344,17.6725x-83.1425,26.2664x-80.8398,34.5726x-77.6514,42.5x-73.6122,49.9617x-68.7664,56.8761x-63.1673,63.1673x-56.8761,68.7664x-49.9617,73.6122x-42.5,77.6514x-34.5726,80.8398x-26.2664,83.1425x-17.6725,84.5344x-8.88492,85x0\n\
bed_temperature = 0\n\
before_layer_gcode =\n\
bottom_solid_layers = 3\n\
bridge_acceleration = 0\n\
bridge_fan_speed = 100\n\
bridge_flow_ratio = 1\n\
bridge_speed = 60\n\
brim_width = 0\n\
complete_objects = 0\n\
cooling = 1\n\
default_acceleration = 0\n\
disable_fan_first_layers = 3\n\
dont_support_bridges = 1\n\
duplicate_distance = 6\n\
end_gcode = M104 S0 ; turn off temperature\\nG28 X0  ; home X axis\\nM84     ; disable motors\\n\n\
external_fill_pattern = rectilinear\n\
external_perimeter_extrusion_width = 0\n\
external_perimeter_speed = 35%\n\
external_perimeters_first = 0\n\
extra_perimeters = 1\n\
extruder_clearance_height = 20\n\
extruder_clearance_radius = 20\n\
extruder_offset = 0x0\n\
extrusion_axis = E\n\
extrusion_multiplier = 1\n\
extrusion_width = 0\n\
fan_always_on = 0\n\
fan_below_layer_time = 60\n\
filament_colour = #FFFFFF\n\
filament_diameter = 1.75\n\
fill_angle = 45\n\
fill_density = 20%\n\
fill_pattern = honeycomb\n\
first_layer_acceleration = 0\n\
first_layer_bed_temperature = 0\n\
first_layer_extrusion_width = 200%\n\
first_layer_height = 0.35\n\
first_layer_speed = 15\n\
first_layer_temperature = 0\n\
gap_fill_speed = 20\n\
gcode_arcs = 0\n\
gcode_comments = 0\n\
gcode_flavor = reprap\n\
infill_acceleration = 0\n\
infill_every_layers = 1\n\
infill_extruder = 1\n\
infill_extrusion_width = 0\n\
infill_first = 0\n\
infill_only_where_needed = 0\n\
infill_overlap = 15%\n\
infill_speed = 58\n\
interface_shells = 0\n\
layer_gcode =\n\
layer_height = 0.2\n\
max_fan_speed = 100\n\
max_print_speed = 80\n\
max_volumetric_speed = 0\n\
min_fan_speed = 35\n\
min_print_speed = 10\n\
min_skirt_length = 0\n\
notes =\n\
nozzle_diameter = 0.4\n\
octoprint_apikey =\n\
octoprint_host =\n\
only_retract_when_crossing_perimeters = 1\n\
ooze_prevention = 0\n\
output_filename_format = [input_filename_base].gcode\n\
overhangs = 1\n\
perimeter_acceleration = 0\n\
perimeter_extruder = 1\n\
perimeter_extrusion_width = 0\n\
perimeter_speed = 40\n\
perimeters = 3\n\
post_process =\n\
pressure_advance = 0\n\
raft_layers = 3\n\
resolution = 0\n\
retract_before_travel = 2\n\
retract_layer_change = 0\n\
retract_length = 2\n\
retract_length_toolchange = 10\n\
retract_lift = 0.1\n\
retract_restart_extra = 0\n\
retract_restart_extra_toolchange = 0\n\
retract_speed = 40\n\
seam_position = aligned\n\
skirt_distance = 6\n\
skirt_height = 1\n\
skirts = 1\n\
slowdown_below_layer_time = 5\n\
small_perimeter_speed = 15\n\
solid_infill_below_area = 70\n\
solid_infill_every_layers = 0\n\
solid_infill_extruder = 1\n\
solid_infill_extrusion_width = 0\n\
solid_infill_speed = 20\n\
spiral_vase = 0\n\
standby_temperature_delta = -5\n\
start_gcode = G28 ; home all axes\\nG1 Z5 F5000 ; lift nozzle\\nX3F3\\nX3F2\\nX3F1\\n\n\
support_material = 0\n\
support_material_angle = 0\n\
support_material_contact_distance = 0.2\n\
support_material_enforce_layers = 0\n\
support_material_extruder = 1\n\
support_material_extrusion_width = 0\n\
support_material_interface_extruder = 1\n\
support_material_interface_layers = 3\n\
support_material_interface_spacing = 0.1\n\
support_material_interface_speed = 100%\n\
support_material_pattern = pillars\n\
support_material_spacing = 2.5\n\
support_material_speed = 60\n\
support_material_threshold = 0\n\
temperature = 0\n\
thin_walls = 1\n\
threads = 2\n\
toolchange_gcode =\n\
top_infill_extrusion_width = 0\n\
top_solid_infill_speed = 15\n\
top_solid_layers = 3\n\
travel_speed = 88\n\
use_firmware_retraction = 0\n\
use_relative_e_distances = 0\n\
use_volumetric_e = 0\n\
vibration_limit = 0\n\
wipe = 0\n\
xy_size_compensation = 0\n\
z_offset = 0'

ini_constraint = {
    'avoid_crossing_perimeters': [binary],
    'bed_shape': [constant],
    'bed_temperature': [constant],
    'before_layer_gcode': [free],
    'bottom_solid_layers': [int_range, 0, 20],
    'bridge_acceleration': False,
    'bridge_fan_speed': False,
    'bridge_flow_ratio': False,
    'bridge_speed': False,
    'brim_width': False,
    'complete_objects': False,
    'cooling': False,
    'default_acceleration': False,
    'disable_fan_first_layers': False,
    'dont_support_bridges': False,
    'duplicate_distance': False,
    'end_gcode': False,
    'external_fill_pattern': False,
    'external_perimeter_extrusion_width': False,
    'external_perimeter_speed': [percentage],
    'external_perimeters_first': False,
    'extra_perimeters': False,
    'extruder_clearance_height': False,
    'extruder_clearance_radius': False,
    'extruder_offset': False,
    'extrusion_axis': False,
    'extrusion_multiplier': False,
    'extrusion_width': False,
    'fan_always_on': False,
    'fan_below_layer_time': False,
    'filament_colour': False,
    'filament_diameter': False,
    'fill_angle': False,
    'fill_density': [percentage],
    'fill_pattern': False,
    'first_layer_acceleration': False,
    'first_layer_bed_temperature': [constant],
    'first_layer_extrusion_width': [percentage, 0, 1666],
    'first_layer_height': False,
    'first_layer_speed': False,
    'first_layer_temperature': False,
    'gap_fill_speed': False,
    'gcode_arcs': False,
    'gcode_comments': [constant],
    'gcode_flavor': False,
    'infill_acceleration': False,
    'infill_every_layers': False,
    'infill_extruder': False,
    'infill_extrusion_width': False,
    'infill_first': False,
    'infill_only_where_needed': False,
    'infill_overlap': [percentage],
    'infill_speed': False,
    'interface_shells': False,
    'layer_gcode': False,
    'layer_height': False,
    'max_fan_speed': [percentage],
    'max_print_speed': False,
    'max_volumetric_speed': False,
    'min_fan_speed': False,
    'min_print_speed': False,
    'min_skirt_length': False,
    'notes': False,
    'nozzle_diameter': False,
    'octoprint_apikey': False,
    'octoprint_host': False,
    'only_retract_when_crossing_perimeters': False,
    'ooze_prevention': False,
    'output_filename_format': False,
    'overhangs': False,
    'perimeter_acceleration': False,
    'perimeter_extruder': False,
    'perimeter_extrusion_width': False,
    'perimeter_speed': False,
    'perimeters': False,
    'post_process': False,
    'pressure_advance': False,
    'raft_layers': False,
    'resolution': False,
    'retract_before_travel': False,
    'retract_layer_change': False,
    'retract_length': False,
    'retract_length_toolchange': False,
    'retract_lift': False,
    'retract_restart_extra': False,
    'retract_restart_extra_toolchange': False,
    'retract_speed': False,
    'seam_position': False,
    'skirt_distance': False,
    'skirt_height': False,
    'skirts': False,
    'slowdown_below_layer_time': False,
    'small_perimeter_speed': False,
    'solid_infill_below_area': False,
    'solid_infill_every_layers': False,
    'solid_infill_extruder': False,
    'solid_infill_extrusion_width': False,
    'solid_infill_speed': False,
    'spiral_vase': False,
    'standby_temperature_delta': False,
    'start_gcode': False,
    'support_material': False,
    'support_material_angle': False,
    'support_material_contact_distance': False,
    'support_material_enforce_layers': False,
    'support_material_extruder': False,
    'support_material_extrusion_width': False,
    'support_material_interface_extruder': False,
    'support_material_interface_layers': False,
    'support_material_interface_spacing': False,
    'support_material_interface_speed': [percentage],
    'support_material_pattern': False,
    'support_material_spacing': False,
    'support_material_speed': False,
    'support_material_threshold': False,
    'temperature': False,
    'thin_walls': False,
    'threads': False,
    'toolchange_gcode': False,
    'top_infill_extrusion_width': False,
    'top_solid_infill_speed': False,
    'top_solid_layers': [int_range, 0, 20],
    'travel_speed': False,
    'use_firmware_retraction': False,
    'use_relative_e_distances': False,
    'use_volumetric_e': False,
    'vibration_limit': False,
    'wipe': False,
    'xy_size_compensation': False,
    'z_offset': False,
}
